### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by wj123-wj** [nullquant/ComfyUI-BrushNet#146]
Hello, author. I’ve encountered some issues and would like to ask for your help.
The following is the incorrect code

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, PowerPaintCLIPLoader, PowerPaint, CutForInpaint
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 15, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet\brushnet.py", line 10, in <module>
    from diffusers.models.attention_processor import (
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\attention_processor.py", line 34, in <module>
    import xformers
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\xformers\__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\xformers\checkpoint.py", line 57, in <module>
    from torch.utils.checkpoint import _ignored_ops  # type: ignore
ImportError: cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)

Cannot import D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet module for custom nodes: cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)

**Comment by nullquant** [comment]
Which PyTorch version are you using? Can you post a full ComfyUI starting log?

**Comment by wj123-wj** [comment]
Hello author，It should be this version ，pytorch version: 2.1.2+cu118，
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-08 09:06:40.105717
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\python.exe
** ComfyUI Path: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3
** Log path: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy-main
   0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
   0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
   5.6 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32577 MB
pytorch version: 2.1.2+cu118
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.1.2+cu118)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\web
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['D:\\ComfyUI-aki-v1.3\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'D:\\ComfyUI-aki-v1.3\\ComfyUI-aki-v1.3\\models\\animatediff_models']
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\xformers\checkpoint.py", line 53, in <module>
    from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)

**Comment by wj123-wj** [comment]
[10.8.log](https://github.com/user-attachments/files/17286310/10.8.log)

**Comment by wj123-wj** [comment]
Thank you for your reply

**Comment by nullquant** [comment]
This is a problem with `xformers` library. You probably updated it, but it was build with "PyTorch 2.4.0+cu121" while you have 2.1.2. Brushnet nodes just tried to load xformers and you've  got the error. I suggest revert xformers to [an old version](https://github.com/facebookresearch/xformers/releases/tag/v0.0.23.post1), or reinstall new pytorch.

**Comment by wj123-wj** [comment]
Thank you for your answer. It has been fixed now, thank you.
